name: CI Pipeline
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432  
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0
      - run: bun install
      - run: bun run tsc --noEmit
      - run: bun run eslint --max-warnings=0
      - run: bun test --coverage
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres